import { Area, Task } from './types';
import { getIsoToday } from './utils';

const todayIso = getIsoToday();

export const INITIAL_AREAS: Area[] = [
  {
    id: 'medai',
    name: 'MedAI',
    desc: 'Rozwój produktu i projekty AI w medycynie',
    color: '#2f80ed',
    position: 1000,
  },
  {
    id: 'firma',
    name: 'Spółka',
    desc: 'Sprawy firmowe, księgowość, podatki',
    color: '#18a66a',
    position: 2000,
  },
  {
    id: 'private',
    name: 'Prywatne',
    desc: 'Sprawy osobiste, dom, rodzina',
    color: '#8757c7',
    position: 3000,
  },
  {
    id: 'dev',
    name: 'Development',
    desc: 'Projekty techniczne, narzędzia, automatyzacja',
    color: '#f2992e',
    position: 4000,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: '1',
    title: 'Przygotować raport z analizy naczyń',
    description: 'Sporządzić szczegółowy podsumowujący raport z wynikami ostatniej analizy.',
    area: 'medai',
    status: 'added',
    date: todayIso,
    time: '10:00',
    priority: 'Wysoki',
    position: 1000,
  },
  {
    id: '2',
    title: 'Poprawić segmentację naczyń – model CT',
    description: 'Optymalizacja progowania i redukcja szumów w skanach tomograficznych.',
    area: 'medai',
    status: 'doing',
    date: todayIso,
    time: '09:00',
    priority: 'Pilny',
    position: 1000,
  },
  {
    id: '3',
    title: 'Problemy z importem plików DICOM – błąd Python',
    description: 'Sprawdzić parsowanie nagłówków pydicom i wykluczyć pliki bez znaczników pacjenta.',
    area: 'medai',
    status: 'blocked',
    date: todayIso,
    time: '',
    priority: 'Pilny',
    position: 1000,
  },
  {
    id: '4',
    title: 'Wstępna analiza danych klinicznych',
    description: 'Weryfikacja kompletnosć próbek.',
    area: 'medai',
    status: 'done',
    date: todayIso,
    time: '',
    priority: 'Normalny',
    position: 1000,
  },
  {
    id: '5',
    title: 'Zebrać dane do prezentacji dla inwestora',
    description: 'Wykresy ze skutecznością klasyfikacji naczyń.',
    area: 'medai',
    status: 'added',
    date: todayIso,
    time: '',
    priority: 'Normalny',
    position: 2000,
  },
  {
    id: '6',
    title: 'Integracja z Ansys (CFD)',
    description: 'Eksport geometrii 3D do formatu STL.',
    area: 'medai',
    status: 'doing',
    date: todayIso,
    time: '',
    priority: 'Normalny',
    position: 2000,
  },
  {
    id: '7',
    title: 'Przygotować wersję PDF raportu',
    description: 'Formatowanie i eksport.',
    area: 'medai',
    status: 'doing',
    date: todayIso,
    time: '',
    priority: 'Normalny',
    position: 3000,
  },
  {
    id: '8',
    title: 'Przygotowanie środowiska chmurowego (AWS)',
    description: 'Instancje EC2 GPU.',
    area: 'medai',
    status: 'done',
    date: todayIso,
    time: '',
    priority: 'Normalny',
    position: 2000,
  },
  {
    id: '9',
    title: 'Telefon do księgowej',
    description: 'Faktury za ubiegły miesiąc.',
    area: 'firma',
    status: 'added',
    date: todayIso,
    time: '11:00',
    priority: 'Normalny',
    position: 1000,
  },
  {
    id: '10',
    title: 'Sprawdzić pliki na SFTP',
    description: 'Weryfikacja sum kontrolnych.',
    area: 'dev',
    status: 'doing',
    date: todayIso,
    time: '16:00',
    priority: 'Normalny',
    position: 1000,
  },
  {
    id: '11',
    title: 'Spotkanie z zespołem',
    description: 'Omówienie celów na ten kwartał.',
    area: 'private',
    status: 'added',
    date: todayIso,
    time: '17:00',
    priority: 'Normalny',
    position: 1000,
  },
  {
    id: '12',
    title: 'Środowisko testowe – konfiguracja',
    description: 'Wdrożenie Docker Compose.',
    area: 'medai',
    status: 'done',
    date: todayIso,
    time: '',
    priority: 'Normalny',
    position: 3000,
  },
  {
    id: '13',
    title: 'Koncepcja architektury systemu',
    description: 'Diagramy komponentów.',
    area: 'medai',
    status: 'done',
    date: todayIso,
    time: '',
    priority: 'Normalny',
    position: 4000,
  },
  {
    id: '14',
    title: 'Skontaktować się z radiologiem w sprawie testów',
    description: 'Konsultacja wyników weryfikacji.',
    area: 'medai',
    status: 'added',
    date: todayIso,
    time: '',
    priority: 'Normalny',
    position: 3000,
  },
];
